---
- hosts: all
  become: yes
  tasks:
    - name: Ensure Docker Python libraries are installed
      pip:
        name: 
          - docker
          - requests

    - name: Stop existing container
      docker_container:
        name: streamlit-devops-app
        state: absent

    - name: Pull the latest Docker image
      docker_image:
        name: streamlit-devops-app:{{ image_tag }}
        source: local

    - name: Run the Docker container
      docker_container:
        name: streamlit-devops-app
        image: streamlit-devops-app:{{ image_tag }}
        ports:
          - "8501:8501"
        restart_policy: always
